//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_network.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentMenu
    {
        public int CommentMenuID { get; set; }
        public string contentss { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> MenuinformationID { get; set; }
        public string commenttime { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        public virtual Menuinformation Menuinformation { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
