//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_network.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menuinformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menuinformation()
        {
            this.BuImage = new HashSet<BuImage>();
            this.CommentMenu = new HashSet<CommentMenu>();
        }
    
        public int MenuinformationID { get; set; }
        public string MenuinformationName { get; set; }
        public string abstractss { get; set; }
        public string TypeName { get; set; }
        public string Technology { get; set; }
        public string yield { get; set; }
        public string MenuinformationImg { get; set; }
        public string Dishes { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> TypetID { get; set; }
        public string difficulty { get; set; }
        public string Setuptime { get; set; }
        public string CookingTime { get; set; }
        public string People { get; set; }
        public string Ingredients { get; set; }
        public string directions { get; set; }
        public string calorie { get; set; }
        public string carbohydrate { get; set; }
        public string eggwhite { get; set; }
        public string cholesterol { get; set; }
        public string fat { get; set; }
        public string commenttime { get; set; }
        public Nullable<int> viewscount { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuImage> BuImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentMenu> CommentMenu { get; set; }
        public virtual Typetypes Typetypes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
