//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_network.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChowhoundNetEntities11 : DbContext
    {
        public ChowhoundNetEntities11()
            : base("name=ChowhoundNetEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuImage> BuImage { get; set; }
        public virtual DbSet<CommentMenu> CommentMenu { get; set; }
        public virtual DbSet<Menuinformation> Menuinformation { get; set; }
        public virtual DbSet<Typetypes> Typetypes { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
