//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_network.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typetypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typetypes()
        {
            this.Menuinformation = new HashSet<Menuinformation>();
        }
    
        public int TypetypesID { get; set; }
        public string TypetypesName { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menuinformation> Menuinformation { get; set; }
    }
}
