//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe_network.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.CommentMenu = new HashSet<CommentMenu>();
            this.Menuinformation = new HashSet<Menuinformation>();
        }
    
        public int userID { get; set; }
        public string Account { get; set; }
        public string UName { get; set; }
        public string userpic { get; set; }
        public Nullable<int> phone { get; set; }
        public string pwd { get; set; }
        public string sex { get; set; }
        public string Birthday { get; set; }
        public Nullable<int> isDelete { get; set; }
        public string discriptss { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentMenu> CommentMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menuinformation> Menuinformation { get; set; }
    }
}
